---
apiVersion: "lerentis.uploadfilter24.eu/v1beta5"
kind: BitwardenSecret
metadata:
  name: test
spec:
  content:
    - element:
        secretName: username
        secretRef: nameofUser
        secretScope: login
    - element:
        secretName: password
        secretRef: passwordOfUser
        secretScope: login
  id: "88781348-c81c-4367-9801-550360c21295"
  name: "test-secret"
  namespace: "default"


---
apiVersion: "lerentis.uploadfilter24.eu/v1beta5"
kind: BitwardenSecret
metadata:
  name: test3
spec:
  content:
    - element:
        secretName: username
        secretRef: nameofUser
        secretScope: login
  itemName: "Application Credentials"
  collectionPath: "Software/Team/Component"
  name: "test-secret-2"
  namespace: "default"
